- hosts: mons
  sudo: true
  environment: proxy_env
  tasks:
    - shell: creates=/opt/golang/bin/godep bash -c "source /etc/profile.d/00golang.sh; go get github.com/kr/godep"
    - file: path=/usr/share/docker/plugins state=directory
  roles:
  - ceph-mon
  - ceph-osd
  - etcd

- hosts: osds
  sudo: True
  environment: proxy_env
  roles:
  - ceph-osd

- hosts: mdss
  sudo: True
  environment: proxy_env
  roles:
  - ceph-mds

- hosts: rgws
  sudo: True
  environment: proxy_env
  roles:
  - ceph-radosgw
