- hosts: mons
  sudo: true
  environment: proxy_env
  tasks:
    - service:
        name: docker
        state: stopped
    - shell: sleep 10
    - copy: src=docker dest=/usr/bin/docker
    - service:
        name: docker
        state: started
    - shell: creates=/usr/local/go/bin/go curl -L https://storage.googleapis.com/golang/go1.4.2.linux-amd64.tar.gz | tar -xvz -C /usr/local
    - file: path=/opt/golang/src/github.com/contiv state=directory
    - shell: creates=/opt/golang/bin/godep bash -c "source /etc/profile.d/00golang.sh; go get github.com/kr/godep"
    - file: path=/usr/share/docker/plugins state=directory
    - copy: src=../volmaster.json dest=/etc/volmaster.json
  roles:
  - ceph-mon
  - ceph-restapi

- hosts: osds
  sudo: True
  roles:
  - ceph-osd

- hosts: mdss
  sudo: True
  roles:
  - ceph-mds

- hosts: rgws
  sudo: True
  roles:
  - ceph-radosgw
