- hosts: mons
  sudo: true
  environment: proxy_env
  tasks:
    - yum: "name={{ item }}"
      with_items:
        - gcc
        - git
        - mercurial
        - librbd1-devel
        - perl
        - curl
    - service:
        name: docker
        state: stopped
    - shell: curl https://master.dockerproject.org/linux/amd64/docker -o /usr/bin/docker
    - service:
        name: docker
        state: started
    - shell: creates=/usr/local/go/bin/go curl -L https://storage.googleapis.com/golang/go1.4.2.linux-amd64.tar.gz | tar -xvz -C /usr/local
    - file: path=/opt/golang/src/github.com/contiv state=directory
    - copy: 
        dest: /etc/profile.d/00golang.sh
        content: "export PATH=/opt/golang/bin:/usr/local/go/bin:$PATH\nexport GOPATH=/opt/golang"
    - name: "read client.admin credentials"
      shell: >
        cat /etc/ceph/ceph.client.admin.keyring | perl -e 'undef $/; $line = <>; $line =~ s/.*= //sg; print $line'
      register: client_secret 
    - copy:
        dest: /etc/rbdconfig.json
        mode: 0600
        content: "{ \"secret\": \"{{ client_secret.stdout }}\", \"monitor_ip\": \"{{ hostvars['mon0']['ansible_' + monitor_interface]['ipv4']['address'] }}\", \"username\": \"admin\" }\n"
    - file: src=/vagrant dest=/opt/golang/src/github.com/contiv/volplugin state=link
    - shell: creates=/opt/golang/bin/godep bash -c "source /etc/profile.d/00golang.sh; go get github.com/kr/godep"
    - file: path=/usr/share/docker/plugins state=directory
    - copy: src=../volmaster.json dest=/etc/volmaster.json
  roles:
  - ceph-mon
  - ceph-restapi

- hosts: osds
  sudo: True
  roles:
  - ceph-osd

- hosts: mdss
  sudo: True
  roles:
  - ceph-mds

- hosts: rgws
  sudo: True
  roles:
  - ceph-radosgw
